workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

      - name: Build App Bundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab

  ios-release:
    name: iOS Release Build
    max_build_duration: 60

    integrations:
      app_store_connect: apple-codemagic

    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.zarasamad.handiroti
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Apply Codemagic provisioning profiles
        script: |
          xcode-project use-profiles

      - name: Build signed IPA
        script: |
          xcode-project build-ipa             --workspace "$XCODE_WORKSPACE"             --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
